import { describe, expect, it } from "vitest";
import entry from "./index.js";
import { getToolPluginMetadata } from "openclaw/plugin-sdk/tool-plugin";

describe("fieldops-tools", () => {
  it("declares tool metadata", () => {
    expect(getToolPluginMetadata(entry)?.tools.map((tool) => tool.name)).toEqual([
      "list_assets",
      "get_asset",
      "register_asset",
      "verify_asset",
      "update_asset_status",
      "list_consumables",
      "adjust_consumable_quantity",
      "list_sites",
      "get_site",
      "register_site",
      "get_site_inventory",
      "list_loadouts",
      "create_loadout",
      "resolve_loadout",
      "checkout_asset",
      "return_checkout",
      "list_overdue_checkouts",
      "create_order",
      "list_orders",
      "update_order_status",
      "compile_purchase_order",
      "request_transfer",
      "update_transfer_status",
      "list_vendors",
      "add_vendor",
      "send_purchase_order",
      "mark_purchase_order_fulfilled",
      "list_crew_members",
      "register_crew_member",
      "assign_shift",
      "assign_shifts_batch",
      "confirm_shift",
      "list_shifts",
      "log_timeclock_event",
      "get_crew_status",
      "list_alerts",
      "resolve_alert",
      "list_vehicles",
      "get_vehicle",
      "register_vehicle",
      "log_vehicle_location",
      "start_trip",
      "end_trip",
      "list_vehicle_trips",
      "log_document",
      "list_documents",
      "list_expiring_documents",
    ]);
  });
});
